//! Clipboard interaction and monitoring module
//! Reads and writes text, HTML, and images, utilizing robust fallbacks

use arboard::{Clipboard, ImageData};
use std::borrow::Cow;
use std::hash::{Hash, Hasher};
use std::process::{Command, Stdio};
use std::io::Write;
use std::sync::atomic::{AtomicU64, Ordering};
use crate::backend::simulator::is_x11;

/// Atomic registers containing the hash of the last pasted text and image.
/// The background watcher reads these to ignore events generated by our own app.
pub static LAST_TEXT_HASH: AtomicU64 = AtomicU64::new(0);
pub static LAST_IMAGE_HASH: AtomicU64 = AtomicU64::new(0);

/// Get current text from clipboard with arboard or command-line fallback
pub fn get_current_text() -> Result<String, String> {
    let mut ctx = Clipboard::new().map_err(|e| e.to_string())?;
    if let Ok(text) = ctx.get_text() {
        return Ok(text);
    }
    
    // Command-line tool fallback
    if is_x11() {
        let output = Command::new("xclip")
            .args(["-selection", "clipboard", "-o"])
            .output();
        if let Ok(out) = output {
            if out.status.success() {
                return Ok(String::from_utf8_lossy(&out.stdout).into_owned());
            }
        }
    } else {
        let output = Command::new("wl-paste")
            .arg("-n")
            .output();
        if let Ok(out) = output {
            if out.status.success() {
                return Ok(String::from_utf8_lossy(&out.stdout).into_owned());
            }
        }
    }

    Err("Failed to read clipboard text".to_string())
}

/// Robustly set text to clipboard
pub fn set_text_robust(text: &str) -> Result<(), String> {
    let hash = calculate_hash(text);
    LAST_TEXT_HASH.store(hash, Ordering::SeqCst);

    let mut ctx = Clipboard::new().map_err(|e| e.to_string())?;
    if ctx.set_text(text.to_owned()).is_ok() {
        return Ok(());
    }

    // Command line fallback
    if is_x11() {
        let mut child = Command::new("xclip")
            .args(["-selection", "clipboard", "-i"])
            .stdin(Stdio::piped())
            .spawn()
            .map_err(|e| e.to_string())?;
        if let Some(mut stdin) = child.stdin.take() {
            stdin.write_all(text.as_bytes()).ok();
        }
        let _ = child.wait();
    } else {
        let mut child = Command::new("wl-copy")
            .stdin(Stdio::piped())
            .spawn()
            .map_err(|e| e.to_string())?;
        if let Some(mut stdin) = child.stdin.take() {
            stdin.write_all(text.as_bytes()).ok();
        }
        let _ = child.wait();
    }

    Ok(())
}

/// Robustly set HTML content to clipboard
pub fn set_html_robust(html: &str, plain: &str) -> Result<(), String> {
    let hash = calculate_hash(plain);
    LAST_TEXT_HASH.store(hash, Ordering::SeqCst);

    // If command line tools are present, use them for rich formatting
    if is_x11() {
        // xclip supports target formats
        let mut child = Command::new("xclip")
            .args(["-selection", "clipboard", "-t", "text/html", "-i"])
            .stdin(Stdio::piped())
            .spawn()
            .map_err(|e| e.to_string())?;
        if let Some(mut stdin) = child.stdin.take() {
            stdin.write_all(html.as_bytes()).ok();
        }
        let _ = child.wait();
    } else {
        // wl-copy supports mime types
        let mut child = Command::new("wl-copy")
            .args(["-t", "text/html"])
            .stdin(Stdio::piped())
            .spawn()
            .map_err(|e| e.to_string())?;
        if let Some(mut stdin) = child.stdin.take() {
            stdin.write_all(html.as_bytes()).ok();
        }
        let _ = child.wait();
    }

    // fallback set plain text too
    let _ = set_text_robust(plain);
    Ok(())
}

/// Struct containing raw RGBA image dimensions and pixels
#[derive(Clone)]
pub struct ImageRaw {
    pub width: usize,
    pub height: usize,
    pub bytes: Vec<u8>,
}

/// Read image data from clipboard
pub fn get_current_image() -> Result<Option<(ImageRaw, u64)>, String> {
    let mut ctx = Clipboard::new().map_err(|e| e.to_string())?;
    match ctx.get_image() {
        Ok(image) => {
            let bytes = image.bytes.to_vec();
            let hash = calculate_hash(&bytes);
            Ok(Some((
                ImageRaw {
                    width: image.width,
                    height: image.height,
                    bytes,
                },
                hash,
            )))
        }
        Err(arboard::Error::ContentNotAvailable) => Ok(None),
        Err(e) => Err(e.to_string()),
    }
}

/// Robustly write image data to clipboard
pub fn set_image_robust(base64_str: &str, width: u32, height: u32) -> Result<(), String> {
    let bytes = match base64::decode(base64_str) {
        Ok(b) => b,
        Err(_) => return Err("Failed to decode base64 image".to_string()),
    };

    let hash = calculate_hash(&bytes);
    LAST_IMAGE_HASH.store(hash, Ordering::SeqCst);

    let mut ctx = Clipboard::new().map_err(|e| e.to_string())?;
    
    let img_data = ImageData {
        width: width as usize,
        height: height as usize,
        bytes: Cow::Owned(bytes),
    };

    ctx.set_image(img_data).map_err(|e| e.to_string())?;
    Ok(())
}

/// Converts raw RGBA pixels to a Base64-encoded PNG image
pub fn convert_image_to_base64(raw: &ImageRaw) -> Option<String> {
    let mut png_bytes = Vec::new();
    {
        let mut encoder = png::Encoder::new(&mut png_bytes, raw.width as u32, raw.height as u32);
        encoder.set_color(png::ColorType::Rgba);
        encoder.set_depth(png::BitDepth::Eight);
        let mut writer = encoder.write_header().ok()?;
        writer.write_image_data(&raw.bytes).ok()?;
    }
    Some(base64::encode(png_bytes))
}

/// Calculate FNV-1a 64-bit hash
pub fn calculate_hash<T: Hash + ?Sized>(t: &T) -> u64 {
    let mut s = std::collections::hash_map::DefaultHasher::new();
    t.hash(&mut s);
    s.finish()
}
